### PR TITLE
Branch2

### PR DESCRIPTION
**Pull request by CodeOwler**
1- Fixed routing problem. There was a problem with the routing between sign up and sign in. If you went from sign in to sign up and vice versa, it would've just pushed it and not replaced it.
2- Improved validation on fields
3- improved implementation of the onPressed parameter for SignUp and SignIn

### CODE REVIEW

**Comment by abuanwar072** [comment]
Hi,
Thanks for your commit but I will update the code on each episode, that's why right now I'm not able to marge it. Students need the same code.

**Comment by CodeOwler** [comment]
Hello Anwar!
To be frank with you I did not know you have a youtube channel. I was going through GitHub and I thought to check out your project.  Hence I contributed. However, I am really glad that you are teaching on youtube. Keep up the good work ; )

**Comment by phin4real** [comment]
Hello Anwar,
I was wondering if it's possible to use a part of your code in an App I'm trying to create and publish on the store?

**Comment by abuanwar072** [comment]
> Hello Anwar,
> I was wondering if it's possible to use a part of your code in an App I'm trying to create and publish on the store?

Go ahead!

**Pull request closed without merging**
